Upstream
barnstee/UA-CloudPublisher pull request #8
Opened 2024-04-12 12:57 UTC by GoetzGoerisch

2024-04-14 12:50 UTC, barnstee commented
Hi Goetz! Thanks for your contrib. Did you test with the new NuGets?

2024-04-15 06:45 UTC, GoetzGoerisch commented
Hi Erich, yes I did check the basic functionality.

- Connect and subscribe to OPC UA sample server
- Connect and publish to MQTT broker

2024-04-15 06:53 UTC, barnstee commented
OK, thanks. I will merge AFTER HMI, but we should also talk about the goals of replacing the Arm64 build instructions. Are you at HMI?

2024-04-16 10:45 UTC, barnstee commented
Musste wegen einem Security Issue die NuGets schon updaten, bitte einmal die Aenderungen im Projektfile rausnehmen.

2024-05-03 06:39 UTC, GoetzGoerisch commented
@barnstee, could you merge this, or is something needed?

2024-05-03 07:56 UTC, barnstee requested changes

2024-05-03 07:56 UTC, barnstee commented on README.md
> +[![Docker](https://github.com/umati/UA-CloudPublisher/actions/workflows/docker-publish.yml/badge.svg)](https://github.com/umati/UA-CloudPublisher/actions/workflows/docker-publish.yml)
Please fix link to build status.

2024-05-04 04:57 UTC, GoetzGoerisch commented on README.md
> +[![Docker](https://github.com/umati/UA-CloudPublisher/actions/workflows/docker-publish.yml/badge.svg)](https://github.com/umati/UA-CloudPublisher/actions/workflows/docker-publish.yml)
Thank you for catching this, changed.

2024-05-04 13:18 UTC, barnstee approved these changes

2024-05-04 13:21 UTC, merged